server:
  port: 4004

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            ## http://localhost:4005/auth/login
            ## API-GATEWAY -> http://auth-service:4005/login
            ## auth-ecs-service-23555.aws.com
            - id: auth-service-route
              uri: http://host.docker.internal:4005
              predicates:
                - Path=/auth/**
              filters:
                - StripPrefix=1

            - id: patient-service-route
              uri: http://host.docker.internal:4000
              predicates:
                - Path=/api/patients/**
              filters:
                - StripPrefix=1
                - JwtValidation

            - id: api-docs-patient-route
              uri: http://host.docker.internal:4000
              predicates:
                - Path=/api-docs/patients
              filters:
                - RewritePath=/api-docs/patients,/v3/api-docs
                ## CLIENT => http://patient-service:4000/api-docs/patients
                ## API-GATEWAY => http://patient-service:4000/v3/api-docs
            - id: api-doc-auth-route
              uri: http://host.docker.internal:4005
              predicates:
                - Path=/api-docs/auth
              filters:
                - RewritePath=/api-docs/auth,/v3/api-docs